name: app
type: nodejs:18

build:
  flavor: none

web:
  commands:
    start: node main.js
  locations:
    "/":
      root: ""
      passthru: true
      allow: true

relationships:
  db: "db:postgresql"

mounts:
  "/node_modules":
    source: local
    source_path: node_modules

variables:
  env:
    NODE_ENV: "production"
