version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: factureprodb
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/factureprodb
    ports:
      - "3333:3333"
    command: ["node", "wait-for-postgres.js"]
