name: backend
type: "nodejs:18"
build:
  commands:
    - npm install
web:
  commands:
    start: node main.js
  locations:
    "/":
      root: ""
      allow: true
disk: 512
mounts:
  "/data": "shared:data"
relationships:
  database: "db:postgresql"
